org: amirykehara
service: api-alumnos

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  timeout: 29
  iam:
    role: arn:aws:iam::773506457076:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true

  crear:
    handler: CrearAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/crear
          method: post
          cors: true

  modificar:
    handler: ModificarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/modificar
          method: put
          cors: true

  eliminar:
    handler: EliminarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/eliminar
          method: delete
          cors: true

  buscar:
    handler: BuscarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/buscar
          method: post
          cors: true


